# Generated by Django 5.0.6 on 2024-06-22 12:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ecommerceapp", "0002_remove_product_image_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image_path1",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="image_path2",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="image_path3",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="image_path4",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="image_path5",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="image_path6",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
